# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_office',
                'doc_host': 'https://XYZfar.github.io',
                'git_url': 'https://github.com/XYZfar/nbdev_office',
                'lib_path': 'nbdev_office'},
  'syms': {'nbdev_office.core': {'nbdev_office.core.foo': ('core.html#foo', 'nbdev_office/core.py')}}}
